### ISSUE TITLE
load library error

### ISSUE THREAD

**Issue by sploving** [tum-i4/sip-oblivious-hashing#153]
Hello, 
I met the following error:
opt -load /usr/local/lib/libTransforms.so
Error opening '/usr/local/lib/libTransforms.so': libInputDependency.so: cannot open shared object file: No such file or directory
  -load request ignored.

In the /usr/local/lib/ dir, the libTransforms.so file exits. But why still such error? thanks.

**Comment by djwessel** [comment]
Hey, from your included command, it looks like you are just trying to load the libTransforms.so shared object file, but the error occurring is because the libInputDependency.so shared object file isn't also included. Try to load both of them at the same time, like this `opt -load /usr/local/lib/libInputDependency.so -load /usr/local/lib/libTransforms.so`
